apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: arf-init
  name: arf-init
spec:
  containers:
  - image: runlevl4/arfcom:latest
    name: app
    resources: {}
  initContainers:
  - name: init
    image: busybox:1.28
    command: ['sh', '-c', "echo demo of init containers; sleep 10"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
