apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: arfcom
  name: arfcom
spec:
  replicas: 3
  selector:
    matchLabels:
      run: arfcom
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: arfcom
    spec:
      containers:
      - image: runlevl4/arfcom:latest
        imagePullPolicy: Always
        name: arfcom
        resources:
          requests:
            cpu: 25m
            memory: 50M
          limits:
            cpu: 100m
            memory: 100M
        livenessProbe:
          httpGet:
            path: /info
            port: 8000
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
